#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from PIL import Image, ImageOps, ImageTk


DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 64
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
PREVIEW_SCALE = 3

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_OUTPUT_DIR = REPO_ROOT / "src" / "generated" / "engine_bitmaps"
FIT_CHOICES = ("contain", "cover", "stretch")

ASSET_CONFIG = {
    "fm": {
        "file_stem": "fm_bitmap",
        "symbol": "fm_bitmap",
        "label": "FM",
    },
    "karplus": {
        "file_stem": "karplus_bitmap",
        "symbol": "karplus_bitmap",
        "label": "KARPLUS",
    },
}


def validate_threshold(value: int) -> int:
    if not 0 <= value <= 255:
        raise ValueError("threshold must be between 0 and 255")
    return value


def fit_to_display(image: Image.Image, fit_mode: str) -> Image.Image:
    resampling = Image.Resampling.LANCZOS

    if fit_mode == "stretch":
        return image.resize(DISPLAY_SIZE, resampling)

    if fit_mode == "cover":
        return ImageOps.fit(image, DISPLAY_SIZE, method=resampling)

    contained = ImageOps.contain(image, DISPLAY_SIZE, method=resampling)
    canvas = Image.new("L", DISPLAY_SIZE, color=255)
    offset = (
        (DISPLAY_WIDTH - contained.width) // 2,
        (DISPLAY_HEIGHT - contained.height) // 2,
    )
    canvas.paste(contained, offset)
    return canvas


def threshold_image(image: Image.Image, threshold: int, invert: bool) -> Image.Image:
    binary = image.point(lambda pixel: 0 if pixel <= threshold else 255, mode="L")
    if invert:
        binary = ImageOps.invert(binary)
    return binary.convert("1", dither=Image.Dither.NONE)


def format_cpp_array(data: bytes) -> str:
    bytes_per_line = 12
    lines: list[str] = []

    for index in range(0, len(data), bytes_per_line):
        chunk = data[index : index + bytes_per_line]
        formatted = ", ".join(f"0x{byte:02X}" for byte in chunk)
        lines.append(f"    {formatted},")

    return "\n".join(lines)


def build_header(
    *,
    symbol: str,
    bmp_bytes: bytes,
    source_path: Path,
    threshold: int,
    invert: bool,
    fit_mode: str,
) -> str:
    return f"""#pragma once

#include <cstddef>
#include <cstdint>

namespace engine_bitmaps {{

// Generated by tools/generate_engine_bitmap.py
// Source: {source_path.name}
// Threshold: {threshold}
// Inverted: {"yes" if invert else "no"}
// Fit mode: {fit_mode}
inline constexpr std::uint8_t {symbol}[] = {{
{format_cpp_array(bmp_bytes)}
}};

inline constexpr std::size_t {symbol}_len = sizeof({symbol});

}} // namespace engine_bitmaps
"""


def render_bitmap(
    input_path: Path,
    *,
    threshold: int,
    invert: bool,
    fit_mode: str,
) -> Image.Image:
    with Image.open(input_path) as source_image:
        grayscale = source_image.convert("L")
        fitted = fit_to_display(grayscale, fit_mode)
        return threshold_image(fitted, threshold, invert)


def write_outputs(
    input_path: Path,
    *,
    slot: str,
    threshold: int,
    invert: bool,
    fit_mode: str,
    output_dir: Path,
) -> tuple[Path, Path]:
    config = ASSET_CONFIG[slot]
    bmp_path = output_dir / f"{config['file_stem']}.bmp"
    header_path = output_dir / f"{config['file_stem']}.hpp"

    output_dir.mkdir(parents=True, exist_ok=True)
    bitmap = render_bitmap(
        input_path,
        threshold=threshold,
        invert=invert,
        fit_mode=fit_mode,
    )
    bitmap.save(bmp_path, format="BMP")

    bmp_bytes = bmp_path.read_bytes()
    header_contents = build_header(
        symbol=config["symbol"],
        bmp_bytes=bmp_bytes,
        source_path=input_path,
        threshold=threshold,
        invert=invert,
        fit_mode=fit_mode,
    )
    header_path.write_text(header_contents, encoding="ascii")
    return bmp_path, header_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert an input image into a 128x64 1-bit BMP and matching C++ "
            "header for the PicoSynth engine select menu."
        )
    )
    parser.add_argument(
        "input_image",
        nargs="?",
        type=Path,
        help="Path to the source image (PNG/JPG/BMP/etc.).",
    )
    parser.add_argument(
        "--slot",
        choices=tuple(ASSET_CONFIG.keys()),
        help="Engine menu slot to update.",
    )
    parser.add_argument(
        "--threshold",
        type=int,
        default=128,
        help="Threshold from 0-255 used to convert the image to 1-bit.",
    )
    parser.add_argument(
        "--invert",
        action="store_true",
        help="Invert the thresholded image before exporting.",
    )
    parser.add_argument(
        "--fit",
        choices=FIT_CHOICES,
        default="contain",
        help=(
            "How to map the source image onto the 128x64 display. "
            "'contain' keeps aspect ratio with white padding."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory that will receive the generated .bmp and .hpp files.",
    )
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Launch the simple visual GUI.",
    )
    args = parser.parse_args()

    if not args.gui and (args.input_image is None or args.slot is None):
        args.gui = True

    return args


class BitmapGeneratorGui:
    def __init__(self) -> None:
        self.root = tk.Tk()
        self.root.title("PicoSynth Engine Bitmap Generator")
        self.root.resizable(False, False)

        self.input_path: Path | None = None
        self.preview_image = None
        self.preview_photo: ImageTk.PhotoImage | None = None

        self.slot_var = tk.StringVar(value="fm")
        self.fit_var = tk.StringVar(value="contain")
        self.threshold_var = tk.IntVar(value=128)
        self.invert_var = tk.BooleanVar(value=False)
        self.path_var = tk.StringVar(value="No image selected")
        self.status_var = tk.StringVar(
            value="Load an image to preview the 128x64 bitmap."
        )

        self._build_ui()
        self._update_preview()

    def _build_ui(self) -> None:
        main = ttk.Frame(self.root, padding=12)
        main.grid(row=0, column=0, sticky="nsew")

        controls = ttk.Frame(main)
        controls.grid(row=0, column=0, sticky="nw", padx=(0, 12))

        ttk.Button(controls, text="Load Image", command=self._choose_file).grid(
            row=0, column=0, sticky="ew"
        )
        ttk.Label(
            controls,
            textvariable=self.path_var,
            wraplength=280,
            justify="left",
        ).grid(row=1, column=0, sticky="w", pady=(8, 12))

        ttk.Label(controls, text="Engine Slot").grid(row=2, column=0, sticky="w")
        slot_box = ttk.Combobox(
            controls,
            textvariable=self.slot_var,
            state="readonly",
            values=tuple(ASSET_CONFIG.keys()),
            width=14,
        )
        slot_box.grid(row=3, column=0, sticky="ew", pady=(2, 10))

        ttk.Label(controls, text="Fit Mode").grid(row=4, column=0, sticky="w")
        fit_box = ttk.Combobox(
            controls,
            textvariable=self.fit_var,
            state="readonly",
            values=FIT_CHOICES,
            width=14,
        )
        fit_box.grid(row=5, column=0, sticky="ew", pady=(2, 10))
        fit_box.bind("<<ComboboxSelected>>", lambda _event: self._update_preview())

        ttk.Label(controls, text="Threshold").grid(row=6, column=0, sticky="w")
        threshold_scale = ttk.Scale(
            controls,
            from_=0,
            to=255,
            orient="horizontal",
            variable=self.threshold_var,
            command=lambda _value: self._on_threshold_change(),
        )
        threshold_scale.grid(row=7, column=0, sticky="ew")
        self.threshold_label = ttk.Label(controls, text="128")
        self.threshold_label.grid(row=8, column=0, sticky="w", pady=(2, 10))

        invert_check = ttk.Checkbutton(
            controls,
            text="Negative / invert image",
            variable=self.invert_var,
            command=self._update_preview,
        )
        invert_check.grid(row=9, column=0, sticky="w", pady=(0, 12))

        ttk.Button(controls, text="Save Bitmap", command=self._save_bitmap).grid(
            row=10, column=0, sticky="ew"
        )
        ttk.Label(
            controls,
            textvariable=self.status_var,
            wraplength=280,
            justify="left",
        ).grid(row=11, column=0, sticky="w", pady=(10, 0))

        preview_frame = ttk.LabelFrame(main, text="128x64 Preview", padding=8)
        preview_frame.grid(row=0, column=1, sticky="n")
        self.preview_label = ttk.Label(preview_frame)
        self.preview_label.grid(row=0, column=0)

    def _choose_file(self) -> None:
        file_name = filedialog.askopenfilename(
            title="Choose source image",
            filetypes=[
                ("Image files", "*.png *.jpg *.jpeg *.bmp *.gif *.tif *.tiff"),
                ("All files", "*.*"),
            ],
        )
        if not file_name:
            return

        self.input_path = Path(file_name)
        self.path_var.set(str(self.input_path))
        self.status_var.set("Preview updated.")
        self._update_preview()

    def _on_threshold_change(self) -> None:
        threshold = int(round(self.threshold_var.get()))
        self.threshold_var.set(threshold)
        self.threshold_label.config(text=str(threshold))
        self._update_preview()

    def _build_preview_photo(self, image: Image.Image) -> ImageTk.PhotoImage:
        preview = image.convert("L").resize(
            (DISPLAY_WIDTH * PREVIEW_SCALE, DISPLAY_HEIGHT * PREVIEW_SCALE),
            Image.Resampling.NEAREST,
        )
        return ImageTk.PhotoImage(preview)

    def _update_preview(self) -> None:
        threshold = int(round(self.threshold_var.get()))
        self.threshold_var.set(threshold)
        self.threshold_label.config(text=str(threshold))

        if self.input_path is None:
            blank = Image.new("L", (DISPLAY_WIDTH, DISPLAY_HEIGHT), color=255)
            self.preview_photo = self._build_preview_photo(blank)
            self.preview_label.configure(image=self.preview_photo)
            return

        try:
            bitmap = render_bitmap(
                self.input_path,
                threshold=validate_threshold(threshold),
                invert=self.invert_var.get(),
                fit_mode=self.fit_var.get(),
            )
        except Exception as exc:
            self.status_var.set(f"Preview error: {exc}")
            return

        self.preview_image = bitmap
        self.preview_photo = self._build_preview_photo(bitmap)
        self.preview_label.configure(image=self.preview_photo)

    def _save_bitmap(self) -> None:
        if self.input_path is None:
            messagebox.showerror("No image selected", "Load an image first.")
            return

        try:
            threshold = validate_threshold(int(round(self.threshold_var.get())))
            bmp_path, header_path = write_outputs(
                self.input_path,
                slot=self.slot_var.get(),
                threshold=threshold,
                invert=self.invert_var.get(),
                fit_mode=self.fit_var.get(),
                output_dir=DEFAULT_OUTPUT_DIR,
            )
        except Exception as exc:
            messagebox.showerror("Export failed", str(exc))
            self.status_var.set(f"Export failed: {exc}")
            return

        self.status_var.set(
            f"Saved {bmp_path.name} and {header_path.name} for {self.slot_var.get()}."
        )
        messagebox.showinfo(
            "Export complete",
            f"BMP: {bmp_path}\nHeader: {header_path}",
        )

    def run(self) -> int:
        self.root.mainloop()
        return 0


def run_cli(args: argparse.Namespace) -> int:
    if args.input_image is None or args.slot is None:
        print("error: CLI mode requires input_image and --slot", file=sys.stderr)
        return 1

    try:
        threshold = validate_threshold(args.threshold)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    input_path = args.input_image.resolve()
    output_dir = args.output_dir.resolve()

    if not input_path.is_file():
        print(f"error: input image does not exist: {input_path}", file=sys.stderr)
        return 1

    bmp_path, header_path = write_outputs(
        input_path,
        slot=args.slot,
        threshold=threshold,
        invert=args.invert,
        fit_mode=args.fit,
        output_dir=output_dir,
    )

    print(f"Wrote {ASSET_CONFIG[args.slot]['label']} bitmap BMP to: {bmp_path}")
    print(f"Wrote {ASSET_CONFIG[args.slot]['label']} bitmap header to: {header_path}")
    return 0


def main() -> int:
    args = parse_args()

    if args.gui:
        return BitmapGeneratorGui().run()

    return run_cli(args)


if __name__ == "__main__":
    raise SystemExit(main())
